LINEAR ALGEBRA,
Linear algebra is a branch of mathematics that focuses on the study of vector spaces and linear mappings between these spaces. It deals with structures that are linear, such as linear equations, linear transformations, and linear combinations.
The general linear equations are represented as:

a1x1 + a2x2............ + an xn = b
a - represents the coefficients.
x - represents the unknown.
b - represents the constant.

 why learning linear algebra is important:
* 		Foundation for Advanced Mathematics: Linear algebra provides the foundation for many advanced mathematical concepts and techniques. It serves as a bridge between basic algebra and more complex mathematical structures.
* 		Understanding Space and Geometry: It helps in understanding and manipulating geometric objects and spaces, making it valuable in fields like computer graphics, computer vision, and 3D modeling.
* 		Solving Systems of Equations: Linear algebra is essential for solving systems of linear equations, which arise in diverse real-world problems, including engineering, physics, economics, and optimization.
* 		Data Analysis and Statistics: Linear algebra is at the core of many data analysis and statistical techniques. Operations like matrix factorization and eigendecomposition are used in data reduction and dimensionality reduction.
* 		Machine Learning and Deep Learning: Linear algebra is a fundamental building block of machine learning and deep learning algorithms. Neural networks, for example, involve extensive matrix operations.
* 		Computer Graphics and Animation: It's crucial in computer graphics for tasks like transformations, rotations, and rendering.
* 		Physics and Engineering: Linear algebra is used to model physical systems and solve problems in fields like mechanics, electromagnetics, and control theory.
* 		Economics and Finance: It's employed in economic modeling, portfolio optimization, and financial analysis.
* 		Optimization: Linear programming, a mathematical method for optimizing objective functions, relies heavily on linear algebra.


2.VECTORS, COMBINING AND SCALING

Vectors represent quantities with both magnitude and direction.
combining vectors involve addition, and scaling vectors involving multipling them by a scalar (a single numerical value).

As you know vector is a physical quantity that has both magnitude and direction.
A vector space is defined as the collection of objects called vectors, which may be added together and multiplied (i.e. scaled) by numbers, called scalars. Generally, real numbers are taken as scalars, but there exist vector spaces with scalar multiplication by non-real numbers, i.e. complex numbers, or naturally any field.

In [2]:
import numpy as np
#Define two vector as numpy array
vector1 = np.array([2, 3])
vector2 = np.array([1, -1])

#vector addition
resultVector = vector1 + vector2
print(resultVector)

[3 2]


In [3]:
#scalar multiplication
scalar = 6
scaledVector = scalar * vector1
print(scaledVector)

[12 18]


In [4]:
#Scalar multiplication
scalar = 2
scaledVector = scalar * resultVector
print(scaledVector)

[6 4]


3. Transforming vectors and matrices

Transforming Vectors:
In linear algebra, vectors represent quantities with both magnitude and direction.
Transforming a vector means applying a linear transformation to it, often represented as a matrix multiplication.
This transformation can change the vector's position, orientation, or scale, depending on the matrix used.
Common transformations include translation, rotation, scaling, and shearing.

Transforming Matrices:
Matrices are rectangular arrays of numbers.
Transforming matrices typically refers to operations like matrix multiplication, addition, and subtraction.
In computer graphics and transformations, matrices are used to represent various transformations applied to objects or spaces.
Transforming matrices can be used to change the position, orientation, or shape of objects in 2D or 3D space.


In [5]:
import numpy as np
#Define a 2D vector as a colomn matrix[x, y]
vector = np.array([[2],
                   [3]])

#Define a 2D transformation matrix for scaling and rotation
#Example: scale by a factor of 2 and rotation by 45 degrees(in radians)
# convert degrees to radians

theta = np.radians(45)
scaleFactor = 2
transformationMatrix = np.array([[scaleFactor * np.cos(theta), -scaleFactor * np.sin(theta)],
                                  [scaleFactor * np.sin(theta), scaleFactor * np.cos(theta)]])

#Perform the transformation by multiplying the vector with the matrices
transformedVector = np.array(transformationMatrix * vector)
print(vector)
print(transformationMatrix)
print(transformedVector)

[[2]
 [3]]
[[ 1.41421356 -1.41421356]
 [ 1.41421356  1.41421356]]
[[ 2.82842712 -2.82842712]
 [ 4.24264069  4.24264069]]


In [6]:
#TRANSFORMING VECTORS AS MATRICES
import numpy as np 

In [7]:
#Create a matrix
matrix = np.array([[1,2],[3,4],[5,6]]) 
print(matrix)

[[1 2]
 [3 4]
 [5 6]]


In [8]:
#Create a vector

#Create a vector as a row
vector_row = np.array([1,2,3])
print(vector_row)

#Create a vector as a column
vector_column = np.array([[1],[2],[3]])
print(vector_column)

[1 2 3]
[[1]
 [2]
 [3]]


In [9]:
#A linear map is referred to as a linear transformation
#Example 1:
#Python function accepts one vector and provides one in return(mapping)
#Transformation from R^2 to R^3
def T(V):
    W = np.zeros((3,1))
    W[0,0] = 2*V[0,0]
    W[2,0] = V[1,0]
    return W

V = np.array([[3],[5]])
W = T(V)

print(V, '\n\n', W)
#This can be described with th formula; T([v1,v2]) = [2v1,0,v2]

[[3]
 [5]] 

 [[6.]
 [0.]
 [5.]]


In [10]:
#Transformation defined as matrix multiplication 
#Example 2:
#L: R^3 to R^3 can be defined as L(X) = AX
#We define a function for this transformation as well
def L(V):
    A = np.array([[1,1,0],[1,0,2],[3,1,-1]])
    W = A@V
    return W

V = np.array([[1],[3],[5]])
W = T(V)

print(V, '\n\n', W)


[[1]
 [3]
 [5]] 

 [[2.]
 [0.]
 [3.]]


In [11]:
#Example 3
#Compositions; if two transformations are to be applied, one after the other, it is common to combine them to form 
#wat is known as a compostion.
 
#FROM EXAMPLES BEFORE
#if we take T: R^2 to R^3 and L: R^3 to R^3, We could define LoT: R^2 to R^3
#We calculate the output by calling the functions from examples before in order, using output from T as input to L

V = np.array([[3],[5]])
composition_output = L(T(V))
print(composition_output)

[[ 6.]
 [16.]
 [13.]]


In [12]:
pip install scipy 


In [13]:
from scipy import linalg 

In [14]:
#Invertibility
#The transformation is invertible if it is possible to map all vectors in the output space back to the input space 
#linear transformation L, is invertible if it has an inverse

def L_inverse(V):
    A = np.array([[1,1,0],[1,0,2],[3,1,-1]])
    A_inverse = linalg.inv(A)
    W = A_inverse@V
    return W

V = np.array([[1],[3],[5]])
print(L(V), '\n')
print(L_inverse(L(V)))



[[ 4]
 [11]
 [ 1]] 

[[1.]
 [3.]
 [5.]]


4. System of linear equations and inverse matrices

A system of linear equations can be represented in matrix form using a coefficient matrix, a variable matrix, and a constant matrix.
Linear equation is used to solve systems of linear equations. Inverse matrices play a crucial role in solving such systems
To solve a system of linear equations using an inverse matrix, let A be the coefficient matrix, let X be the variable matrix, and let B be the constant matrix. Thus, we want to solve a system AX=B.

A Linear system of m equation in n unknown x1,x2......xn is a set of equation of the form.
Linear algebra is used to solve systems of linear equations. Inverse matrices play a crucial role in solving such systems.

In [15]:
import numpy as np
#coefficient matrix 
A = np. array([[2, 3],
                [1, -1]])

# right hand side vector
b = np. array([8, 1])

#solving the system of equations
x = np.linalg.solve(A, b)
print(x)

[2.2 1.2]


In [16]:
import numpy as np

A = np.array([[2, 3], [1, -1]])
B = np.array([8, 1])
# solving the system of equations
x = np.linalg.solve(A,B)
print(x)


[2.2 1.2]


In [17]:
#consider the system of linear equations
# ax + y + z = 6
# a2y + 5z = -4
# a2x + 5y - z = 27
#This is the same as:
#[1 1 1][x] = [6]
#[0 2 5][y] = [4]
#[2 5 -1][z] = [27]
# A       X     B
#A*X = B
#X = B/A = B*A-1

In [18]:
import numpy as np
A= np.array([[1, 1, 1], [0, 2, 5], [2, 5, -1]])
B= np.array([[6], [4],[27]])
X = np.linalg.solve(A,B)
print(X)

[[ 2.71428571]
 [ 4.14285714]
 [-0.85714286]]


In [19]:
import numpy as np
A = np.array([[2,3], [1,-1]])
b = np.array([8,1])
#solving the system of equations
x = np.linalg.solve(A,b)
print(x)

[2.2 1.2]


In [20]:
#finding inverse of a matrix
A_inv = np.linalg.inv(A)

5. Dot products

The dot product (or inner product) of two vectors is a scalar value that represents the projection of one vector onto another.


In [21]:
import numpy as np

In [22]:
#defining two arrays
a=np.array([1,2,3])
b=np.array([4,5,6])

In [23]:
#calculating the dot product using numpy
dot_product=np.dot(a,b)
print(dot_product)

32


In [24]:
#calculate the dot product using the @ operator
dot_product2=a@b
print(dot_product2)

32


In [25]:
#import numpy as np
vector1 = np.array([2, 3])
vector2 = np. array([1,-1])

dotProduct = np.dot(vector1, vector2)
print(dotProduct)

-1


6. Matrix decompositionMatrix Decomposition

A matrix decomposition is a way of reducing a matrix into its constituent parts.
It is an approach that can simplify more complex matrix operations that can be performed on the decomposed matrix rather than on the original matrix itself.
A common analogy for matrix decomposition is the factoring of numbers, such as the factoring of 10 into 2 x 5. For this reason, matrix decomposition is also called matrix factorization. Like factoring real values, there are many ways to decompose a matrix, hence there are a range of different matrix decomposition techniques.
Two simple and widely used matrix decomposition methods are the LU matrix decomposition and the QR matrix decomposition.
Next, we will take a closer look at each of these methods.

LU Matrix Decomposition
The LU decomposition is for square matrices and decomposes a matrix into L and U components.
1	A = L . U
Or, without the dot notation.
1	A = LU
Where A is the square matrix that we wish to decompose, L is the lower triangle matrix and U is the upper triangle matrix.
The factors L and U are triangular matrices. The factorization that comes from elimination is A = LU.
The LU decomposition is found using an iterative numerical process and can fail for those matrices that cannot be decomposed or decomposed easily.
A variation of this decomposition that is numerically more stable to solve in practice is called the LUP decomposition, or the LU decomposition with partial pivoting.
1	A = P . L . U
The rows of the parent matrix are re-ordered to simplify the decomposition process and the additional P matrix specifies a way to permute the result or return the result to the original order. There are also other variations of the LU.
The LU decomposition is often used to simplify the solving of systems of linear equations, such as finding the coefficients in a linear regression, as well as in calculating the determinant and inverse of a matrix.
The LU decomposition can be implemented in Python with the lu() function. More specifically, this function calculates an LPU decomposition.
Matrix decomposition techniques like Singular Value Decomposition (SVD) and Eigenvalue Decomposition (EVD) are used to factorize matrices into simpler forms for various applications.

The example below first defines a 3×3 square matrix. The LU decomposition is calculated, then the original matrix is reconstructed from the components.




In [26]:
pip install scipy

Note: you may need to restart the kernel to use updated packages.


In [27]:
# LU decomposition
from numpy import array
from scipy.linalg import lu
# define a square matrix
A = array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(A)
# LU decomposition
P, L, U = lu(A)
print(P)
print(L)
print(U)
# reconstruct
B = P.dot(L).dot(U)
print(B)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
[[1.         0.         0.        ]
 [0.14285714 1.         0.        ]
 [0.57142857 0.5        1.        ]]
[[7.         8.         9.        ]
 [0.         0.85714286 1.71428571]
 [0.         0.         0.        ]]
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


Cholesky Decomposition

The Cholesky decomposition is for square symmetric matrices where all eigenvalues are greater than zero, so-called positive definite matrices.
For our interests in machine learning, we will focus on the Cholesky decomposition for real-valued matrices and ignore the cases when working with complex numbers.
The decomposition is defined as follows:
1	A = L . L^T
Or without the dot notation:
1	A = LL^T
Where A is the matrix being decomposed, L is the lower triangular matrix and L^T is the transpose of L.
The decompose can also be written as the product of the upper triangular matrix, for example:
1	A = U^T . U
Where U is the upper triangular matrix.
The Cholesky decomposition is used for solving linear least squares for linear regression, as well as simulation and optimization methods.

When decomposing symmetric matrices, the Cholesky decomposition is nearly twice as efficient as the LU decomposition and should be preferred in these cases.

While symmetric, positive definite matrices are rather special, they occur quite frequently in some applications, so their special factorization, called Cholesky decomposition, is good to know about. When you can use it, Cholesky decomposition is about a factor of two faster than alternative methods for solving linear equations.

The Cholesky decomposition can be implemented in NumPy by calling the cholesky() function. The function only returns L as we can easily access the L transpose as needed.

The example below defines a 3×3 symmetric and positive definite matrix and calculates the Cholesky decomposition, then the original matrix is reconstructed.

In [28]:
12	# Cholesky decomposition
from numpy import array
from numpy.linalg import cholesky
# define a 3x3 matrix
A = array([[2, 1, 1], [1, 2, 1], [1, 1, 2]])
print(A)
# Cholesky decomposition
L = cholesky(A)
print(L)
# reconstruct
B = L.dot(L.T)
print(B)

[[2 1 1]
 [1 2 1]
 [1 1 2]]
[[1.41421356 0.         0.        ]
 [0.70710678 1.22474487 0.        ]
 [0.70710678 0.40824829 1.15470054]]
[[2. 1. 1.]
 [1. 2. 1.]
 [1. 1. 2.]]


QR Matrix Decomposition

The QR decomposition is for m x n matrices (not limited to square matrices) and decomposes a matrix into Q and R components.
1	A = Q . R
Or, without the dot notation.
1	A = QR
Where A is the matrix that we wish to decompose, Q a matrix with the size m x m, and R is an upper triangle matrix with the size m x n.
The QR decomposition is found using an iterative numerical method that can fail for those matrices that cannot be decomposed, or decomposed easily.
Like the LU decomposition, the QR decomposition is often used to solve systems of linear equations, although is not limited to square matrices.
The QR decomposition can be implemented in NumPy using the qr() function. By default, the function returns the Q and R matrices with smaller or ‘reduced’ dimensions that is more economical. We can change this to return the expected sizes of m x m for Q and m x n for R by specifying the mode argument as ‘complete’, although this is not required for most applications.

The example below defines a 3×2 matrix, calculates the QR decomposition, then reconstructs the original matrix from the decomposed elements.

In [29]:
# QR decomposition
from numpy import array
from numpy.linalg import qr
# define a 3x2 matrix
A = array([[1, 2], [3, 4], [5, 6]])
print(A)
# QR decomposition
Q, R = qr(A, 'complete')
print(Q)
print(R)
# reconstruct
B = Q.dot(R)
print(B)

[[1 2]
 [3 4]
 [5 6]]
[[-0.16903085  0.89708523  0.40824829]
 [-0.50709255  0.27602622 -0.81649658]
 [-0.84515425 -0.34503278  0.40824829]]
[[-5.91607978 -7.43735744]
 [ 0.          0.82807867]
 [ 0.          0.        ]]
[[1. 2.]
 [3. 4.]
 [5. 6.]]


In [30]:
import numpy as np
#define a martix
A = np.array([[1, 2],
              [3, 4],
              [5, 6]])

# performm SVD
U, S, VT = np.linalg.svd(A)

print(U)
print(S)
print(VT)

[[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]
[9.52551809 0.51430058]
[[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]
